title: Haoming 的网站
description: 我的学习与记录
url: "https://haoming58.github.io"
theme: minima
# baseurl 通常保持空，除非仓  库不是 xxx.github.io 这种
# baseurl: ""
author: Haoming

navigation:
  - name: 主页
    link: /
  - name: 关于我
    link: /about
  - name: 博客
    link: /blog

avatar_url: https://github.com/haoming58.png

social:
  - name: GitHub
    url: https://github.com/haoming58
    icon: github
  - name: Email
    url: mailto:your.email@example.com
    icon: mail
  - name: RSS
    url: /feed.xml
    icon: rss