# Site settings
title: "Haoming's Website | 浩明的网站"
description: "热爱技术的开发者，专注于编程、天线设计和知识分享 | A passionate developer focused on programming, antenna design and knowledge sharing"
url: "https://haoming58.github.io"
baseurl: "/"
author:
  name: "Haoming"
  email: "your.email@example.com"
  url: "https://haoming58.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
twitter:
  username: haoming58
  card: summary
facebook:
  app_id: 
  publisher: 
  admins: 
logo: /assets/images/profile/profile.jpg
social:
  links:
    - https://github.com/haoming58
    - mailto:your.email@example.com
    - /feed.xml
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: zh_CN

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never